### ISSUE TITLE
Is there a way to use this with metals?

### ISSUE THREAD

**Issue by jsatk** [VonHeikemen/lsp-zero.nvim#161]
https://github.com/scalameta/nvim-metals

I love the idea of an all-in-one don't-have-to-think-too-much LSP set up for Neovim. But Metals has to be installed differently than other LSPs.  Metals is still working for me however the keybindings aren't set up properly. Is there a way to tell lsp-zero to enable the keybindings for metals and/or scala files?

**Comment by VonHeikemen** [comment]
There is a function called [build_options()](https://github.com/VonHeikemen/lsp-zero.nvim/blob/v1.x/doc/md/api-reference.md#build_optionsserver-opts), with it you can create the options for the LSP.

```lua
local metals_opts = require('lsp-zero').build_options('metals', {})
```

And I guess you can pass that to nvim-metals. The documenation says the setup function has the same signature as `vim.lsp.start_client()`, so this should work.

```lua
require("metals").initialize_or_attach(metals_opts)
```

If it doesn't, you can use the function `metals_opts.on_attach` in an autocommand or whatever method nvim-metals uses.

**Comment by ckipp01** [comment]
Hey 👋🏼 author of nvim-metals here. 

> The documenation says the setup function has the same signature as vim.lsp.start_client(), so this should work.

The shape is _mostly_ the same, meaning that it accounts for all the existing thigs that `start_client()` does, but it also has some metals specific things in it like `settings`, which you may have configured. So if you are going to call `build_options` make sure you actually merge it with your existing `require("metals").bare_config()` and your settings _before_ you pass it to `initialize_or_attach`.

Looking through:

https://github.com/VonHeikemen/lsp-zero.nvim/blob/9852ce92056d95ca9268155db484e9b4806d8c2d/lua/lsp-zero/server.lua#L27-L50

I'm guessing that the `set_capabilities` and `on_attach` that lsp-zero calls is what you want, depending on how it sets up the default mappings. Some of the other stuff in there you actually really don't want, specifically the the `root_dir` detection as with Scala this won't work as expected since nvim-metals has quite a bit of stuff it needs to do to ensure the correct root, no matter where you open. Mainly, checking for nested build files, etc. So I think you might be better to figure out what in `build_options` is actually needed and call those specifically rather than calling `build_options`.

**Comment by VonHeikemen** [comment]
If you want to be on the safe side you can just take `.capabilities` and `.on_attach` from the result of `build_options`. Really those two are the only one lsp-zero sets, everything else empty by default.

**Comment by jsatk** [comment]
I wanted to update this w/ what I found works very well for me (so far). 

For metals you need to set `useGlobalExecutable` to `true`.

```lua
local metals_config = require("metals").bare_config()

metals_config.settings = {
  useGlobalExecutable = true, -- So we can use LSP Zero.  This means we have to keep Metals up-to-date ourselves.
}
```

And then for LSP Zero set metals to `force_setup`.

```lua
local lsp = require('lsp-zero').preset({
  name = 'minimal',
  set_lsp_keymaps = true,
  manage_nvim_cmp = true,
  suggest_lsp_servers = true,
})

lsp.configure('metals', { force_setup = true })
```

This has been working well for me.
