### ISSUE TITLE
Diagnostic in status line?

### ISSUE THREAD

**Issue by 9mm** [VonHeikemen/lsp-zero.nvim#297]
Hey,

I am coming from vim-ale and it puts the error in the status line. So far this is what I have:

```
    lsp.setup()

    vim.diagnostic.config({
      virtual_text = false,
      update_in_insert = false,
      --underline = false,
    })
```

I have googled around for some time bit it seems quite confusing where I actually put some of this code... am I missing something, ie.. is there an easier way? Or do I need to resort to these large blocks of code

**Comment by 9mm** [comment]
I actually was looking at lualine solutions but i dont want it to appear in the actual lualine, but below, much simpler, like this: (this is vim-ale)

![](https://user-images.githubusercontent.com/1386207/258985840-cf926c4a-ceee-47e9-9381-bbebd8a7592e.png)

This is as close as I can get which is 👎🏼 

![](https://user-images.githubusercontent.com/1386207/258985918-55ec9ad1-9e2f-4da8-841c-f5f62d64f9b2.png)

**Comment by VonHeikemen** [comment]
I'm still not sure what you want. But you can get the diagnostics using the function `vim.diagnostic.get`.

If you have an error/warning you can print it in the message area.

```lua
lua print(vim.diagnostic.get(0)[1].message)
```

This will get the message of the first diagnostic in the buffer. If there isn't any diagnostic you'll get a lua error, because you will be trying to access the `message` property of an "empty value".

**Comment by 9mm** [comment]
Interesting, yes thats basically what I'm looking for. Now I suppose the question is, how would I make occur only for the currently focused line with the cursor?

I'll just keep searching. Thanks for your help!
