### ISSUE TITLE
Undefined gloabl 'vim' wont go away after configuring lsp.lua

### ISSUE THREAD

**Issue by kamerado** [VonHeikemen/lsp-zero.nvim#307]
I have everything setup but inside of my config files i get errors of "undefined global 'vim' " popping up next to the lines that contain vim at the beginning.

in my lsp.lua setup I have this 
"""
lsp.configure('lua-language-server', {
    settings = {
        Lua = {
            diagnostics = {
                globals = { 'vim' }
            }
        }
    }
})
"""
does anyone know why this keeps happening????

**Comment by VonHeikemen** [comment]
Because the name of the language server should be `lua_ls`. You have to keep in mind lsp-zero is using [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig), so the servers you want to configure must be on [this list](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md).
