### ISSUE TITLE
What if I don't find my LSP in MASON

### ISSUE THREAD

**Issue by Santiago-Torres14** [VonHeikemen/lsp-zero.nvim#350]
Hey, I'm getting started with Neovim and all of its capabilities. I came across this package because ThePrimagen recommended it in one of his videos.

My issue is that I cannot find my LSP in Mason (`sourcekit-lsp`), I looked at their docs and it's using `lspconfig` in order to set it up, I'm wondering how to add the same keybindings from lsp-zero to lspconfig or where should I put the configuration.

Thanks in advance!

**Comment by VonHeikemen** [comment]
Is it `0 to LSP` tutorial? That video uses an old version of lsp-zero. Make sure you are using lsp-zero version 3 (use the branch `v3.x`). You can use the command `:help lsp-zero-version` to check which version you are using.

If a language server is not available in mason, you have to install it manually. After that, if the language server is supported by `lspconfig` then just call the setup function for it. The list of supported servers is here: [server_configurations.md](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md).

Since sourcekit is already supported by lspconfig this should work.

```lua
local lsp_zero = require('lsp-zero')

lsp_zero.on_attach(function(client, bufnr)
  lsp_zero.default_keymaps({buffer = bufnr})
end)

require('lspconfig').sourcekit.setup({})
```

If the language server is not supported by `lspconfig` you can still add a configuration to make it work. There is a section in the documentation that describes how to do it: [Custom servers](https://github.com/VonHeikemen/lsp-zero.nvim/blob/v3.x/doc/md/lsp.md#custom-servers).

**Comment by Santiago-Torres14** [comment]
That was helpful, thanks!

Now I'm presenting this issue: 

```lua
Error detected while processing /Users/user-name/.config/nvim/after/plugin/lsp.lua:
E5113: Error while calling lua chunk: /Users/user-name/.config/nvim/after/plugin/lsp.lua:86: attempt to call field 'cmp_format' (a nil value)
```

It looks like when I try to set up cmp with the formatting value, `lsp-zero.cmp_format()` is giving a nil value.

**Comment by Santiago-Torres14** [comment]
Here's the code snippet:

```lua
Error detected while processing /Users/santiagotorres/.config/nvim/after/plugin/lsp.lua:
E5113: Error while calling lua chunk: /Users/santiagotorres/.config/nvim/after/plugin/lsp.lua:86: attempt to call field 'cmp_format' (a nil value)
```

**Comment by VonHeikemen** [comment]
Make sure you are using the branch `v3.x` of lsp-zero.
