### ISSUE TITLE
error installing gopls(same thing happend with hls)

### ISSUE THREAD

**Issue by Wordluc** [VonHeikemen/lsp-zero.nvim#377]
gopls
      ▼ Displaying full log
        Installing go package golang.org/x/tools/gopls@v0.15.1…
        spawn: go failed with exit code - and signal -. go is not executable

**Comment by VonHeikemen** [comment]
The problem here is you don't have the tools necessary to download `gopls`. The message `go is not executable` is telling you the command `go` is not available in your system, or at the very least Neovim can't find it.

I'm assuming you are using `mason.nvim` to install these things. mason.nvim only automates the download of language servers (and other tools). For example, if you try to install `intelephense` mason.nvim will just try to execute the command `npm install intelephense`. Which is the same thing you would do on your terminal. That command will fail if `npm` is not available in your system.

Whatever tools you want to download, you need to make sure you meet their requirements.

**Comment by Wordluc** [comment]
thanks
