### ISSUE TITLE
Language Server Conflicts and Attachment Configuration

### ISSUE THREAD

**Issue by jwyce** [VonHeikemen/lsp-zero.nvim#71]
Two examples I've run into issues with are 'denols' and 'tailwindcss-language-server'. If I install denols through mason, a typescript file will detect both tsserver and denols when I really only want one to attach. Similarly, having tailwind lsp installed never attaches even if I'm in a workspace with a tailwind.config.cjs. Is there a way to configure lsp zero on per lsp basis what file to look for to determine whether or not to attach? Am I doing something wrong?

**Comment by VonHeikemen** [comment]
The typescript thing it's probably because both tsserver and denols have `single_file_support` enabled by default.

To configure an lsp server use the function `.configure`.

```lua
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.configure('tsserver', {
  single_file_support = false
})

lsp.setup()
```

Now tailwind. Looks like the project detection does not look for tailwind.config.cjs. It looks for tailwind.config.js or tailwind.config.ts. If you can change the name of the file that should solve the issue. If not you can list the files to look for.

```lua
local root_pattern = require('lspconfig.util').root_pattern

lsp.configure('tailwindcss', {
  root_dir = root_pattern(
    'tailwind.config.js',
    'tailwind.config.cjs',
    'tailwind.config.ts'
  )
})
```
